# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'test-quick' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test-quick

  target 'test-quickTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
